#!/usr/bin/env bash
quizdir=/home/chad/Public/psych

chap(){
    score=0
    attempts=0
    clear
    echo -e "\n\n\n\n\n"
    echo "What chapter would you like to be quized over?"
    printf "    Chapter: "
    eval "read chap"
    check
}


check (){
    if [[ ! -d $quizdir/$chap || ! -f $quizdir/$chap/def ]]; then
        echo "Sorry, either the chapter doesn't exist or the word list doesn't. Try again."
        read -p "Press [Enter] to try again"
        chap
    else
        quiz
    fi
}

quiz(){
    echo $quit
    sort -R $quizdir/$chap/def > $quizdir/$chap/defrand

    trap "rm $quizdir/$chap/defrand" 0 
    linecnt=$(wc -l $quizdir/$chap/defrand) # Get line count of file

    while [[ $attempts -lt $linecnt ]]; do
        line=$(sed -n $(( $attempts + 1 ))p $quizdir/$chap/defrand) # Get the line with the term and definition
        def=$(echo $line | awk -F\| '{print $2}') # Extract definition from line 
        term=$(echo $line | awk -F\| '{print $1}'| tr '[A-Z]' '[a-z]') # Do the same for the term echo "Definition: $def "
        echo "Definition: $def"
        printf "    Term: "
        read guess
        guess="${guess,,}" # For consistency, convert guess to lower case
       if [[ "$guess" == "quit" ]]; then
            clear
            echo -e "\n\n\n\n\n"
            if [[ $attempts -ne 0 ]]; then
                echo "You were $score for $attempts ($(( $score * 100 / $attempts ))%)"
            else
                echo "No score available"
            fi
            echo "Thanks for playing"
            exit
        elif [[ "$guess" == "$term" ]]; then
            clear
            echo -e "\n\n\n\n\n"
            echo "Correct!"
            score=$(( $score + 1 ))
            attempts=$(( $attempts + 1 ))
            echo "You have completed $attempts of $linecnt"
            echo "Percent correct: $(( $score * 100 / $attempts ))%"
        else
            clear
            echo -e "\n\n\n\n\n"
            echo "Sorry, that is incorrect"
            echo "The correct answer was $term"
            attempts=$((  $attempts + 1 ))
            echo "You have completed $attempts of $linecnt"
            echo "Percent correct: $(( $score * 100 / $attempts ))%"
        fi
    done 
    echo -e "\n\n\n\n\n"
    echo "All done!"
    echo "You were $score for $linecnt"
    again
}

again(){
    echo "Do you want to pick a new chapter? [y/N]"
    read goagain
    case $goagain in 
        [Yy]|[Yy][Ee][Ss]) chap 
            ;;
        ""|[Nn]|[Nn][Oo]) clear
            echo "Goodbye!"
            exit 0
            ;;
        *) echo "Sorry that's not an acceptable response"
           again
           ;;
    esac
}
chap
